# This file was generated by GoReleaser. DO NOT EDIT.
cask "reeve" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "03c4681c4fff8b3daccc658fd7346c1d7988ed0ff82e4177415844222f601151"
      url "https://github.com/reeveops/reeve/releases/download/v#{version}/reeve_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4b083d8fdc50b6474a0dc11c4f50d9c077e91e070ab3ba62c8a95775536059c9"
      url "https://github.com/reeveops/reeve/releases/download/v#{version}/reeve_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5f6f606171261b21a223bed2a66abb85e6169ba13b510eb65a741b15c0eabb3b"
      url "https://github.com/reeveops/reeve/releases/download/v#{version}/reeve_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a41cd6fba587be85913ba45e9fa333d865598c4250ae0f9ea9fac6a2c320244"
      url "https://github.com/reeveops/reeve/releases/download/v#{version}/reeve_#{version}_linux_arm64.tar.gz"
    end
  end

  name "reeve"
  desc "PR-native, self-hosted GitOps orchestrator for Pulumi"
  homepage "https://github.com/reeveops/reeve"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reeve"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reeve"]
    end
  end

  # No zap stanza required

end
